version: "3"
services:
  localMongo:
    depends_on:
      - mongodb
    image: shawchandankumar20/localmongo
    container_name: local
    build: .
    ports:
      - 8081:8081
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - MODE=production
    stdin_open: true
    tty: true
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - ./mongo:/data/db