apiVersion: apps/v1
kind: Deployment
metadata:
  name: spatial
  labels:
    app: spatial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spatial
  template:
    metadata:
      labels:
        app: spatial
    spec:
      containers:
      - name: spatial-container
        image: shawchandankumar20/localmongo:latest
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "400Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: spatial-service
spec:
  type: NodePort
  selector:
    app: spatial
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30036
