apiVersion: apps/v1
kind: Deployment
metadata:
  name: spatial
  labels:
    app: spatial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spatial
  template:
    metadata:
      labels:
        app: spatial
    spec:
      containers:
      - name: spatial-container
        image: shawchandankumar20/localmongo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spatial-service
spec:
  type: NodePort
  selector:
    app: spatial
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30036
